#server
server:
  port: 9999
  servlet:
    context-path: /estate
---
#config
spring:
  #favicon
  mvc:
    favicon:
      enabled: false

  #mysql
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/estate?characterEncoding=utf-8&useSSL=true
    name: mysql
    username: root
    password: root

---

mybatis:
    type-aliases-package: com.novawind.estate.mysql.model
    mapper-locations: classpath:mapping/*/*.xml

---

logging:
  level:
    org.springframework: info
    com.novawind.estate.mysql.dao: info



